// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDn9xHYRDF0vRQeYkrfccfU43dgtTC3ZKM',
    appId: '1:15123276780:web:9172c5093d7c93e86856c9',
    messagingSenderId: '15123276780',
    projectId: 'skinscan-ai',
    authDomain: 'skinscan-ai.firebaseapp.com',
    storageBucket: 'skinscan-ai.firebasestorage.app',
    measurementId: 'G-QMF0DE3JT7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBeuUdKGSps2mnV6izHvYhSNUXetieIhiU',
    appId: '1:15123276780:android:441306a5f7798db26856c9',
    messagingSenderId: '15123276780',
    projectId: 'skinscan-ai',
    storageBucket: 'skinscan-ai.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0ujbWDbTj49JX9MMotbmApAt8aV4eEGg',
    appId: '1:15123276780:ios:48ca80a60cdce6bc6856c9',
    messagingSenderId: '15123276780',
    projectId: 'skinscan-ai',
    storageBucket: 'skinscan-ai.firebasestorage.app',
    iosBundleId: 'com.example.skinscanAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0ujbWDbTj49JX9MMotbmApAt8aV4eEGg',
    appId: '1:15123276780:ios:48ca80a60cdce6bc6856c9',
    messagingSenderId: '15123276780',
    projectId: 'skinscan-ai',
    storageBucket: 'skinscan-ai.firebasestorage.app',
    iosBundleId: 'com.example.skinscanAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDn9xHYRDF0vRQeYkrfccfU43dgtTC3ZKM',
    appId: '1:15123276780:web:527059881980007b6856c9',
    messagingSenderId: '15123276780',
    projectId: 'skinscan-ai',
    authDomain: 'skinscan-ai.firebaseapp.com',
    storageBucket: 'skinscan-ai.firebasestorage.app',
    measurementId: 'G-F2LBSYNNJ0',
  );
}
